package com.group_finity.mascot.imagesetchooser;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Displays information about an image set. Used by {@link ImageSetChooser}.
 *
 * @author Shimeji-ee Group
 * @since 1.0.2
 */
public class ImageSetChooserPanel extends JPanel {

    String imageSet;

    public ImageSetChooserPanel() {
        initComponents();
    }

    public ImageSetChooserPanel(String imageSet, String actions,
                                String behaviors, Path imageLocation, String caption) {
        initComponents();

        this.imageSet = imageSet;
        this.caption.setText(caption);
        actionsFile.setText(actions);
        behaviorsFile.setText(behaviors);
        try {
            BufferedImage img = ImageIO.read(Files.newInputStream(imageLocation));
            image.setIcon(new ImageIcon(img.getScaledInstance(60, 60, Image.SCALE_DEFAULT)));
        } catch (IOException e) {
            // Doesn't matter, the image just won't show
        }
    }

    public void setCheckbox(boolean value) {
        checkbox.setSelected(value);
    }

    public String getImageSetName() {
        return imageSet;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        checkbox = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        image = new javax.swing.JLabel();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        pnlLabels = new javax.swing.JPanel();
        caption = new javax.swing.JLabel();
        actionsFile = new javax.swing.JLabel();
        behaviorsFile = new javax.swing.JLabel();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(checkbox);
        jPanel1.add(filler1);

        image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        image.setMaximumSize(new java.awt.Dimension(60, 60));
        image.setMinimumSize(new java.awt.Dimension(60, 60));
        image.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanel1.add(image);
        jPanel1.add(filler2);

        pnlLabels.setMaximumSize(new java.awt.Dimension(32767, 48));
        pnlLabels.setOpaque(false);
        pnlLabels.setLayout(new javax.swing.BoxLayout(pnlLabels, javax.swing.BoxLayout.Y_AXIS));

        caption.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        caption.setText("Builder");
        pnlLabels.add(caption);

        actionsFile.setText("img/Builder/conf/actions.xml");
        pnlLabels.add(actionsFile);

        behaviorsFile.setText("img/Builder/conf/behaviors.xml");
        pnlLabels.add(behaviorsFile);

        jPanel1.add(pnlLabels);
        jPanel1.add(filler3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionsFile;
    private javax.swing.JLabel behaviorsFile;
    private javax.swing.JLabel caption;
    private javax.swing.JCheckBox checkbox;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pnlLabels;
    // End of variables declaration//GEN-END:variables

}
