package com.group_finity.mascot.win;

import com.group_finity.mascot.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Arrays;

/**
 * @author Kilkakon
 */
public class WindowsInteractiveWindowForm extends JDialog {
    private static final String configFile = "./conf/settings.properties";    // Config file name
    ArrayList<String> listData = new ArrayList<>();

    public WindowsInteractiveWindowForm(Frame owner, boolean modal) {
        super(owner, modal);
        initComponents();
        setLocationRelativeTo(null);

        listData.addAll(Arrays.asList(Main.getInstance().getProperties().getProperty("InteractiveWindows", "").split("/")));
        jList1.setListData(listData.toArray(new String[0]));
    }

    public boolean display() {
        setTitle(Main.getInstance().getLanguageBundle().getString("InteractiveWindows"));
        jButton1.setText(Main.getInstance().getLanguageBundle().getString("Add"));
        jButton2.setText(Main.getInstance().getLanguageBundle().getString("Done"));
        jButton3.setText(Main.getInstance().getLanguageBundle().getString("Remove"));
        setVisible(true);
        return true;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        jScrollPane1 = new JScrollPane();
        jList1 = new JList<>();
        jPanel2 = new JPanel();
        jButton1 = new JButton();
        jButton3 = new JButton();
        jButton2 = new JButton();

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Interactive Windows");

        jList1.setModel(new AbstractListModel<String>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            @Override
            public int getSize() {
                return strings.length;
            }

            @Override
            public String getElementAt(int index) {
                return strings[index];
            }
        });
        jScrollPane1.setViewportView(jList1);

        getContentPane().add(jScrollPane1, BorderLayout.CENTER);

        jPanel2.setLayout(new GridLayout(1, 0));

        jButton1.setText("Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel2.add(jButton1);

        jButton3.setText("Remove");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3);

        jButton2.setText("Done");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt)// GEN-FIRST:event_jButton1ActionPerformed
    {// GEN-HEADEREND:event_jButton1ActionPerformed
        // add button
        String inputValue = JOptionPane.showInputDialog(rootPane, Main.getInstance().getLanguageBundle().getString("InteractiveWindowHintMessage"), Main.getInstance().getLanguageBundle().getString("AddInteractiveWindow"), JOptionPane.QUESTION_MESSAGE).trim();
        if (!inputValue.isEmpty() && !inputValue.contains("/")) {
            listData.add(inputValue);
            jList1.setListData(listData.toArray(new String[0]));
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(ActionEvent evt)// GEN-FIRST:event_jButton3ActionPerformed
    {// GEN-HEADEREND:event_jButton3ActionPerformed
        // delete button
        if (jList1.getSelectedIndex() != -1) {
            listData.remove(jList1.getSelectedIndex());
            jList1.setListData(listData.toArray(new String[0]));
        }
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(ActionEvent evt)// GEN-FIRST:event_jButton2ActionPerformed
    {// GEN-HEADEREND:event_jButton2ActionPerformed
        // done button
        try (FileOutputStream output = new FileOutputStream(configFile)) {
            Main.getInstance().getProperties().setProperty("InteractiveWindows", listData.toString().replace("[", "").replace("]", "").replace(", ", "/"));
            Main.getInstance().getProperties().store(output, "Shimeji-ee Configuration Options");
        } catch (Exception e) {
            // Doesn't matter at all
        }
        dispose();
    }// GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        EventQueue.invokeLater(() -> {
            new WindowsInteractiveWindowForm(new JFrame(), true).display();
            System.exit(0);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton jButton1;
    private JButton jButton2;
    private JButton jButton3;
    private JList<String> jList1;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
