module com.group_finity.mascot {
    requires java.desktop;
    requires java.management;
    requires java.logging;
    requires java.scripting;
    requires com.sun.jna;
    requires com.sun.jna.platform;
    requires AbsoluteLayout.RELEASE270;
    requires org.openjdk.nashorn;
    requires org.apache.commons.exec;
    requires com.jthemedetector;
    requires com.formdev.flatlaf;
    requires com.valkryst.VMVC;

    exports com.group_finity.mascot;
    exports com.group_finity.mascot.action;
    exports com.group_finity.mascot.animation;
    exports com.group_finity.mascot.behavior;
    exports com.group_finity.mascot.config;
    exports com.group_finity.mascot.display.controller;
    exports com.group_finity.mascot.display.model;
    exports com.group_finity.mascot.display.view;
    exports com.group_finity.mascot.environment;
    exports com.group_finity.mascot.exception;
    exports com.group_finity.mascot.image;
    exports com.group_finity.mascot.imagesetchooser;
    exports com.group_finity.mascot.menu;
    exports com.group_finity.mascot.platform.generic;
    exports com.group_finity.mascot.platform.mac;
    exports com.group_finity.mascot.platform.mac.jna;
    exports com.group_finity.mascot.platform.virtual;
    exports com.group_finity.mascot.platform.win;
    exports com.group_finity.mascot.platform.win.jna;
    exports com.group_finity.mascot.platform.x11;
    exports com.group_finity.mascot.script;
    exports com.group_finity.mascot.sound;
    exports hqx;
    exports com.group_finity.mascot.platform;
}
