package com.group_finity.mascot;

import javax.swing.*;

/**
 * @author Kilkakon
 */
public class DebugWindow extends JFrame {
    public DebugWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShimejiX = new JLabel();
        lblShimejiXValue = new JLabel();
        lblShimejiYValue = new JLabel();
        lblShimejiY = new JLabel();
        lblWindowX = new JLabel();
        lblWindowY = new JLabel();
        lblWindowWidth = new JLabel();
        lblWindowHeight = new JLabel();
        lblWindowXValue = new JLabel();
        lblWindowYValue = new JLabel();
        lblWindowWidthValue = new JLabel();
        lblWindowHeightValue = new JLabel();
        lblBehaviour = new JLabel();
        lblBehaviourValue = new JLabel();
        lblEnvironmentY = new JLabel();
        lblEnvironmentX = new JLabel();
        lblEnvironmentXValue = new JLabel();
        lblEnvironmentYValue = new JLabel();
        lblEnvironmentWidth = new JLabel();
        lblEnvironmentHeight = new JLabel();
        lblEnvironmentHeightValue = new JLabel();
        lblEnvironmentWidthValue = new JLabel();
        lblActiveIE = new JLabel();
        lblActiveIEValue = new JLabel();

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        lblShimejiX.setText("Shimeji X");

        lblShimejiXValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblShimejiXValue.setText("N/A");

        lblShimejiYValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblShimejiYValue.setText("N/A");

        lblShimejiY.setText("Shimeji Y");

        lblWindowX.setText("Window X");

        lblWindowY.setText("Window Y");

        lblWindowWidth.setText("Window W");

        lblWindowHeight.setText("Window H");

        lblWindowXValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowXValue.setText("N/A");

        lblWindowYValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowYValue.setText("N/A");

        lblWindowWidthValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowWidthValue.setText("N/A");

        lblWindowHeightValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblWindowHeightValue.setText("N/A");

        lblBehaviour.setText("Behaviour");

        lblBehaviourValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblBehaviourValue.setText("N/A");

        lblEnvironmentY.setText("Environment Y");

        lblEnvironmentX.setText("Environment X");

        lblEnvironmentXValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentXValue.setText("N/A");

        lblEnvironmentYValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentYValue.setText("N/A");

        lblEnvironmentWidth.setText("Environment W");

        lblEnvironmentHeight.setText("Environment H");

        lblEnvironmentHeightValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentHeightValue.setText("N/A");

        lblEnvironmentWidthValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblEnvironmentWidthValue.setText("N/A");

        lblActiveIE.setText("Active IE");

        lblActiveIEValue.setHorizontalAlignment(SwingConstants.LEFT);
        lblActiveIEValue.setText("N/A");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblShimejiX)
                                        .addComponent(lblShimejiY)
                                        .addComponent(lblBehaviour)
                                        .addComponent(lblWindowX)
                                        .addComponent(lblWindowY)
                                        .addComponent(lblWindowWidth)
                                        .addComponent(lblWindowHeight)
                                        .addComponent(lblEnvironmentX)
                                        .addComponent(lblEnvironmentY)
                                        .addComponent(lblEnvironmentWidth)
                                        .addComponent(lblEnvironmentHeight)
                                        .addComponent(lblActiveIE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblBehaviourValue, GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblShimejiYValue)
                                                        .addComponent(lblShimejiXValue)
                                                        .addComponent(lblWindowXValue)
                                                        .addComponent(lblWindowYValue)
                                                        .addComponent(lblWindowHeightValue)
                                                        .addComponent(lblEnvironmentHeightValue)
                                                        .addComponent(lblEnvironmentWidthValue)
                                                        .addComponent(lblWindowWidthValue)
                                                        .addComponent(lblEnvironmentXValue)
                                                        .addComponent(lblEnvironmentYValue)
                                                        .addComponent(lblActiveIEValue))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBehaviour)
                                        .addComponent(lblBehaviourValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblShimejiX)
                                        .addComponent(lblShimejiXValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblShimejiYValue)
                                        .addComponent(lblShimejiY))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblActiveIE)
                                        .addComponent(lblActiveIEValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblWindowX)
                                        .addComponent(lblWindowXValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblWindowY)
                                        .addComponent(lblWindowYValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblWindowWidth)
                                        .addComponent(lblWindowWidthValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblWindowHeight)
                                        .addComponent(lblWindowHeightValue, GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEnvironmentXValue)
                                        .addComponent(lblEnvironmentX))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEnvironmentY)
                                        .addComponent(lblEnvironmentYValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEnvironmentWidth)
                                        .addComponent(lblEnvironmentWidthValue))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblEnvironmentHeight)
                                        .addComponent(lblEnvironmentHeightValue))
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void setBehaviour(String text) {
        lblBehaviourValue.setText(text);
    }

    void setShimejiX(int x) {
        lblShimejiXValue.setText(String.format("%d", x));
    }

    void setShimejiY(int y) {
        lblShimejiYValue.setText(String.format("%d", y));
    }

    void setWindowTitle(String title) {
        lblActiveIEValue.setText(title);
    }

    void setWindowX(int x) {
        lblWindowXValue.setText(String.format("%d", x));
    }

    void setWindowY(int y) {
        lblWindowYValue.setText(String.format("%d", y));
    }

    void setWindowWidth(int width) {
        lblWindowWidthValue.setText(String.format("%d", width));
    }

    void setWindowHeight(int height) {
        lblWindowHeightValue.setText(String.format("%d", height));
    }

    void setEnvironmentX(int x) {
        lblEnvironmentXValue.setText(String.format("%d", x));
    }

    void setEnvironmentY(int y) {
        lblEnvironmentYValue.setText(String.format("%d", y));
    }

    void setEnvironmentWidth(int width) {
        lblEnvironmentWidthValue.setText(String.format("%d", width));
    }

    void setEnvironmentHeight(int height) {
        lblEnvironmentHeightValue.setText(String.format("%d", height));
    }

    @Override
    public void setVisible(boolean b) {
        if (b) {
            lblBehaviour.setText(Main.getInstance().getLanguageBundle().getString("Behaviour"));
            lblShimejiX.setText(Main.getInstance().getLanguageBundle().getString("ShimejiX"));
            lblShimejiY.setText(Main.getInstance().getLanguageBundle().getString("ShimejiY"));
            lblActiveIE.setText(Main.getInstance().getLanguageBundle().getString("ActiveIE"));
            lblWindowX.setText(Main.getInstance().getLanguageBundle().getString("WindowX"));
            lblWindowY.setText(Main.getInstance().getLanguageBundle().getString("WindowY"));
            lblWindowWidth.setText(Main.getInstance().getLanguageBundle().getString("WindowWidth"));
            lblWindowHeight.setText(Main.getInstance().getLanguageBundle().getString("WindowHeight"));
            lblEnvironmentX.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentX"));
            lblEnvironmentY.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentY"));
            lblEnvironmentWidth.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentWidth"));
            lblEnvironmentHeight.setText(Main.getInstance().getLanguageBundle().getString("EnvironmentHeight"));
        }
        super.setVisible(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblActiveIE;
    private JLabel lblActiveIEValue;
    private JLabel lblBehaviour;
    private JLabel lblBehaviourValue;
    private JLabel lblEnvironmentHeight;
    private JLabel lblEnvironmentHeightValue;
    private JLabel lblEnvironmentWidth;
    private JLabel lblEnvironmentWidthValue;
    private JLabel lblEnvironmentX;
    private JLabel lblEnvironmentXValue;
    private JLabel lblEnvironmentY;
    private JLabel lblEnvironmentYValue;
    private JLabel lblShimejiX;
    private JLabel lblShimejiXValue;
    private JLabel lblShimejiY;
    private JLabel lblShimejiYValue;
    private JLabel lblWindowHeight;
    private JLabel lblWindowHeightValue;
    private JLabel lblWindowWidth;
    private JLabel lblWindowWidthValue;
    private JLabel lblWindowX;
    private JLabel lblWindowXValue;
    private JLabel lblWindowY;
    private JLabel lblWindowYValue;
    // End of variables declaration//GEN-END:variables
}